development:
  adapter: postgresql
  encoding: unicode
  database: social_proof_production
  pool: 5
  username: postgres
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: social_proof_test
  pool: 5
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: social_proof_development
  pool: 5
  username: postgres
  password: